version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/sources/

    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - redis
      - postgres
      - adminer
    links:
      - redis
      - postgres:postgres
    networks:
      - projectnetwork

  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - projectnetwork

  celery_worker:
    container_name: celery_worker
    restart: always
    build:
      context: .
    command: ["celery", "-A", "payment", "worker", "-l", "info"]
    links:
      - redis
      - postgres:postgres
    depends_on:
      - app
    volumes:
      - .:/sources/
    networks:
      - projectnetwork

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "27474129"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    networks:
      - projectnetwork
    ports:
      - '54321:5432'

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - projectnetwork

volumes:
  postgres: null

networks:
  projectnetwork:
    driver: bridge
